### ISSUE TITLE
Error during installation - fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error connecting[BUG]

### ISSUE THREAD

**Issue by Dude-Bear** [edhenry/chexnet#28]
**Describe the bug**
When I'm trying to run the install command "ansible-playbook -i hosts build_site.yml" I get the following error:

PLAY [Startup Data Cluster] ***************************************************************************************

TASK [Start Kafka service] ***************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}
        to retry, use: --limit @/home/bjoern/chexnet/playbook/build_site.retry

PLAY RECAP ***************************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1

**Desktop (please complete the following information):**
- Description:    Ubuntu 18.04.2 LTS
- Release:        18.04
- Codename:       bionic

**Additional context**
I just started to learn how to program, so hopefully, I described the error good enough. It may just be a simple mistake I'm doing, but I can't finger out what it is. 

Thanks a lot to edhenry for this awesome repository!

**Comment by edhenry** [comment]
Hi @Dude-Bear !

Thanks for the feedback on the repo.

Could you do me a favor and provide the output of running the ansible command with the verbosity turned up?

Something like `ansible-playbook -i hosts build_site.yml -vvvv`

This should provide me with more output from Ansible to help determine the problem.

Thanks!

**Comment by Dude-Bear** [comment]
Good Morning @edhenry,

Thanks a lot for your answer!

This was the response I got after running the suggested command:
![chexnet error one](https://user-images.githubusercontent.com/30493095/58783334-f3257e80-85e0-11e9-8648-d747f63f0339.PNG)
![chexnet error two](https://user-images.githubusercontent.com/30493095/58783341-f882c900-85e0-11e9-9b0c-fb5023f36eff.PNG)

**Comment by edhenry** [comment]
Hey @Dude-Bear - -

Sorry for the delayed reply! It looks like this might be a known ansible issue.

https://github.com/ansible/ansible/issues/38840

Can you upgrading your Ansible version and try again?

Thanks!

**Comment by Dude-Bear** [comment]
Hey @edhenry ,
thank you for your response. Upgrading Ansible solved the problem!
Thanks a lot for your help and the awesome repository!

**Comment by Aliktk** [comment]
@edhenry  @Dude-Bear  sorry to mentioned you people here. I need your help 
I ran the building site and it working after a lot of hard work with the version of ansible. After running the notebook I can't get the probabilities and heatmap for that image its shows error that none type data I am attaching the screenshot too, Please help.


![Screeasnshot from 2021-06-14 15-41-41](https://user-images.githubusercontent.com/37206954/122217084-811dea80-cec6-11eb-9131-af8c3624e31e.png)
